import {
  Tier0Icon,
  Tier1Icon,
  Tier2Icon,
  Tier3Icon,
  Tier4Icon,
  Tier5Icon,
  Tier6Icon,
  Tier7Icon,
  Tier8Icon,
  Tier9Icon,
  Tier10Icon,
  Tier11Icon,
  Tier12Icon,
  Tier13Icon,
  Tier14Icon,
  Tier15Icon,
  Tier16Icon,
  Tier17Icon,
  Tier18Icon,
  Tier19Icon,
  Tier20Icon,
  Tier21Icon,
  Tier22Icon,
  Tier23Icon,
  Tier24Icon,
  Tier25Icon,
  Tier26Icon,
  Tier27Icon,
  Tier28Icon,
  Tier29Icon,
  Tier30Icon,
} from 'assets/svgs';

const solvedacIcon = (tier: number) => {
  return {
    0: <Tier0Icon className='tier0Icon tierIcon' />,
    1: <Tier1Icon className='tier1Icon tierIcon' />,
    2: <Tier2Icon className='tier1Icon tierIcon' />,
    3: <Tier3Icon className='tier1Icon tierIcon' />,
    4: <Tier4Icon className='tier1Icon tierIcon' />,
    5: <Tier5Icon className='tier1Icon tierIcon' />,
    6: <Tier6Icon className='tier2Icon tierIcon' />,
    7: <Tier7Icon className='tier2Icon tierIcon' />,
    8: <Tier8Icon className='tier2Icon tierIcon' />,
    9: <Tier9Icon className='tier2Icon tierIcon' />,
    10: <Tier10Icon className='tier2Icon tierIcon' />,
    11: <Tier11Icon className='tier3Icon tierIcon' />,
    12: <Tier12Icon className='tier3Icon tierIcon' />,
    13: <Tier13Icon className='tier3Icon tierIcon' />,
    14: <Tier14Icon className='tier3Icon tierIcon' />,
    15: <Tier15Icon className='tier3Icon tierIcon' />,
    16: <Tier16Icon className='tier4Icon tierIcon' />,
    17: <Tier17Icon className='tier4Icon tierIcon' />,
    18: <Tier18Icon className='tier4Icon tierIcon' />,
    19: <Tier19Icon className='tier4Icon tierIcon' />,
    20: <Tier20Icon className='tier4Icon tierIcon' />,
    21: <Tier21Icon className='tier5Icon tierIcon' />,
    22: <Tier22Icon className='tier5Icon tierIcon' />,
    23: <Tier23Icon className='tier5Icon tierIcon' />,
    24: <Tier24Icon className='tier5Icon tierIcon' />,
    25: <Tier25Icon className='tier5Icon tierIcon' />,
    26: <Tier26Icon className='tier6Icon tierIcon' />,
    27: <Tier27Icon className='tier6Icon tierIcon' />,
    28: <Tier28Icon className='tier6Icon tierIcon' />,
    29: <Tier29Icon className='tier6Icon tierIcon' />,
    30: <Tier30Icon className='tier6Icon tierIcon' />,
  }[tier];
};

export default solvedacIcon;
